### ISSUE TITLE
unavailable to the example dataset

### ISSUE THREAD

**Issue by Byronxy** [snap-stanford/mars#11]
Hi,
I try to test your workflow in my machine while I could not get the data from your link
https://github.com/snap-stanford/mars/blob/master/benchmark_datasets/cellbench_kolod_pollen.tgz.
Would you please help me to check out?

**Comment by mbrbic** [comment]
Hi, 

You can downloaded from [http://snap.stanford.edu/mars/data/tms-facs-mars.tar.gz](http://snap.stanford.edu/mars/data/tms-facs-mars.tar.gz). I now updated README file. Thanks!
