### ISSUE TITLE
MARS code problems

### ISSUE THREAD

**Issue by elenichri** [snap-stanford/mars#15]
I could not properly install all the requirements.txt for MARS but I somehow went around some of them manually. Now, I have some problems running the _cellbench.ipynb_ notebook. Especially scanpy is quite error-prone. 
When I have the scanpy version specified in requiements.txt (scanpy 1.4.4.post1), scanpy is randomly loaded (in one run I have error and in the other run I don't). 

When it does get imported, I get the error further down the script:
`'tuple' object has no attribute 'tocsr'` when I run the command 
`sc.pp.neighbors(adata, n_neighbors=30, use_rep='X')`

I found online that I need to upgrade scanpy to solve this. When I did so, I got other errors (linked to the umap function)

Also the args_parser library is randomly found (in one run it is found and in another run later it is not found)

Please help me solve these problems. I don't use python, I am used to R. Maybe some of the problems that I face are trivial for python-programmers... Or maybe the requirements.txt is outdated?

Note: I did not create a separate environment to run MARS. I did all the above in my base environment. I have python 3.6 installed via anaconda3.

Thank you very much.

**Comment by mbrbic** [comment]
Hi Elen,

I am sorry but you will need to contact Scanpy developers regarding your issue since this is not related to our code. As written in the requirements, we were using scanpy 1.4.4 and everything worked well. Our requirements file is generated directly from our environment. Perhaps you can try to install a separate environment.

**Comment by elenichri** [comment]
Ok, noted. Thank you for your time.
