### ISSUE TITLE
Provide tutorial for mars.name_cell_types

### ISSUE THREAD

**Issue by Winbuntu** [snap-stanford/mars#22]
Hi, I am wondering if you could provide more guidance for how to generate interpretable names for discovered clusters by calling: mars.name_cell_types(adata, landmarks, cell_type_name_map). 

This was not included in any available tutorial, and the help/comments in the source code are not detailed enough.

**Comment by mbrbic** [comment]
Hi! I now updated the code with better description.

Naming function takes as argument:
- adata: anndata object returned by function train
- landmarks: cell type landmarks also returned by function train
- cell_type_name_map: dictionary with cell type name of previously seen cell types as key, and their cluster idx as value

This function will return dictionary with novel cell type cluster index as key and probabilities to all previously seen cell types as value. 

You can check example of calling this function in [main_TM](https://github.com/snap-stanford/mars/blob/master/main_TM.py) for Tabula Muris data.

**Comment by Winbuntu** [comment]
Thanks for the quick reply! To my understanding, main_TM is the code for the leave-one-tissue-out analysis described in the Nature Methods manuscript? 
And by using **adata, landmarks, scores = mars.train(evaluation_mode=True)** , **scores** are the performance scores?

**Comment by mbrbic** [comment]
That is correct.
