### ISSUE TITLE
Seurat / Reticulate example

### ISSUE THREAD

**Issue by AndrewSkelton** [snap-stanford/mars#4]
Feature Request: Would it be possible to show an example of this using Seurat with the reticulate library?  Possible expanding the [original vignette ](https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html)?

Thanks for the really cool method!

**Comment by mbrbic** [comment]
Hi Andrew,

Our preprocessing code is built upon Scanpy and written in Python (not R). Scanpy already provides preprocessing and clustering [vignette](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html) that follows Seurat's vignette you are referring to.
