### ISSUE TITLE
how to load args_parser and model? 

### ISSUE THREAD

**Issue by Yale73** [snap-stanford/mars#6]
Hi MARS team,

Thanks for such great package. As a beginner, when I try to run your notebook:
```
from args_parser import get_parser
from model.mars import MARS
from model.experiment_dataset import ExperimentDataset
from data.benchmarks import BenchmarkData
import warnings
```

I got an issue that **No module named 'args_parser', 'get_parser', 'model'.** 

I am wondering whether you can help me to load these packages correctly?

Thanks,
Yale

**Comment by mbrbic** [comment]
You can solve this by moving notebook file to the directory where args_parser file is located.

**Comment by Yale73** [comment]
@mbrbic  I did it, but still doesn't work.
