### ISSUE TITLE
NameError: name 'anndata' is not defined

### ISSUE THREAD

**Issue by Yale73** [snap-stanford/mars#7]
Hi MARS team,

I got my loom object from seurat object. But when I run the "anndata.read_loom", I got the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-62-f16757897d08> in <module>
----> 1 adata = anndata.read_loom('~/Skin.loom', sparse=True, cleanup=False, X_name='spliced', obs_names='CellID', obsm_names=None, var_names='Gene', varm_names=None, dtype='float32', **kwargs)

**NameError: name 'anndata' is not defined**
```

Can you help me fix it?

Thanks a bunch!
Yale

**Comment by Yale73** [comment]
I am sure I have installed the anndata

![image](https://user-images.githubusercontent.com/50378244/97231123-45e47500-1798-11eb-8c07-0905a1d1882d.png)

**Comment by mbrbic** [comment]
You need to import anndata and install loompy. This is completely unrelated to MARS code, closing the thread.
