### ISSUE TITLE
ValueError: too many dimensions 'str'  when running MARS

### ISSUE THREAD

**Issue by Yale73** [snap-stanford/mars#8]
Hi MARS team,

Thanks for your help. 

Today I ran a new issue. 

When I ran the `mars = MARS(n_clusters, params, [annotated], unannnotated, pretrain_data)`, 
I got the error:  **ValueError: too many dimensions 'str'** 

Can you help me with it?

Thanks,
Yale

**Comment by Yale73** [comment]
I found it is because I choose the wrong obs. I fixed it.
But after I corrected it, I got new error. `AttributeError: 'Namespace' object has no attribute 'device'`.

Thanks for your patience.
Yale

**Comment by giandrickdabian** [comment]
Hi, how did you solve this issue? I am currently experiencing it now.

**Comment by Yale73** [comment]
@giandrickdabian I gave it up and used singleR package to annotate the cell types.

**Comment by mbrbic** [comment]
@giandrickdabian You should check that the labels you are giving to the MARS are correct. If you have string labels, you need to convert them to numeric. You can check how this is done for Tabula Muris data [here](https://github.com/snap-stanford/mars/blob/1db4c88df0fe8161a2a23e2519ebb48f25ea4343/data/maca_facs.py).

**Comment by giandrick** [comment]
> @giandrickdabian You can check whether the labels you are giving to the MARS are correct. If you have string labels, you need to convert them to numeric. You can check how this is done for Tabula Muris data [here](https://github.com/snap-stanford/mars/blob/1db4c88df0fe8161a2a23e2519ebb48f25ea4343/data/maca_facs.py).

Hey thanks, yes in my notebook you see that i did change them to numeric. I read somewhere something about setting reprocess input to true but idk where exactly to do that
